name: Auto Sync from Upstream

env:
  UPSTREAM_URL: "https://github.com/tidev/titanium_mobile.git"
  UPSTREAM_BRANCH: "master"

on:
  schedule: 
  - cron: "0 0 * * *"
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/tidev/titanium_mobile.git # change this
          upstream_branch: master # change this
          downstream_branch: master # change this
          token: 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

